# Generated by Django 5.0.6 on 2024-06-26 14:45

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_account_balance_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date_time',
            new_name='transaction_time',
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(max_length=4, validators=[account.validators.validate_pin]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
