# Generated by Django 5.0.6 on 2024-07-02 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
