# Generated by Django 5.0.6 on 2024-07-02 13:48

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[user.validators.validate_phone_number]),
        ),
    ]
